In [6]:
# This code cell will be in every one of our chapters in Jupyter Notebook
# The function allows you to see every line of output when the code has multiple lines
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
import pandas as pd
import os

We would like to visualize data for specific points in time a well as across the past decade of data. To do this you wil lbe merging data from 2010 to 2022. Like you practiced in the control structures chapter, you should load in the multi-year ACS data with a for-loop, and a list of file names drawn from the files in the data folder. First make the vectors that the loop will iterate over. 

In this case it is the list of CSV files which we searched for with the argument `if i.endswith('Data.csv)`. The search string can't be just the .csv file extension, because the ACS data dictionaries are also CSV files. You also need a vector of just the years in question, because we will be adding the year as a value in a new column for each loaded dataframe.

In [42]:
path = '../../Data/ACS/DP04/Place/'
csv_files = [i for i in os.listdir(path) if i.endswith('Data.csv')]
csv_files.sort() # need csv_files in chronological order
csv_files
years.remove(2020) # ACS is missing 1-year data in 2020
years

['ACSDP1Y2010.DP04-Data.csv',
 'ACSDP1Y2011.DP04-Data.csv',
 'ACSDP1Y2012.DP04-Data.csv',
 'ACSDP1Y2013.DP04-Data.csv',
 'ACSDP1Y2014.DP04-Data.csv',
 'ACSDP1Y2015.DP04-Data.csv',
 'ACSDP1Y2016.DP04-Data.csv',
 'ACSDP1Y2017.DP04-Data.csv',
 'ACSDP1Y2018.DP04-Data.csv',
 'ACSDP1Y2019.DP04-Data.csv',
 'ACSDP1Y2021.DP04-Data.csv',
 'ACSDP1Y2022.DP04-Data.csv']

[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022]

In [36]:
housing=[]
housing=pd.DataFrame(housing) # ceate empty dataframe to take new data

for i in range(len(csv_files)):
    file_path=path+csv_files[i]
    temp=pd.read_csv(file_path, low_memory=False) # load unique dataframes to a temporary df
    temp['year']=years[i] # add a year variable
    print(csv_files[i],'had',len(temp),'rows and',len(temp.columns),'columns')
    housing=pd.concat([housing,temp]) # concatenate the data into 'housing'
housing.shape

ACSDP1Y2010.DP04-Data.csv had 556 rows and 568 columns
ACSDP1Y2011.DP04-Data.csv had 563 rows and 568 columns
ACSDP1Y2012.DP04-Data.csv had 569 rows and 568 columns
ACSDP1Y2013.DP04-Data.csv had 583 rows and 568 columns
ACSDP1Y2014.DP04-Data.csv had 592 rows and 568 columns
ACSDP1Y2015.DP04-Data.csv had 597 rows and 576 columns
ACSDP1Y2016.DP04-Data.csv had 606 rows and 576 columns
ACSDP1Y2017.DP04-Data.csv had 615 rows and 576 columns
ACSDP1Y2018.DP04-Data.csv had 631 rows and 576 columns
ACSDP1Y2019.DP04-Data.csv had 635 rows and 576 columns
ACSDP1Y2021.DP04-Data.csv had 635 rows and 576 columns
ACSDP1Y2022.DP04-Data.csv had 647 rows and 576 columns

(7229, 577)

Select the variables we will be plotting.
|Variable|New Name|Label|
|:-:|:-:|:-:|
|a|b|c|

In [25]:
housing.tail()

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,year,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
642,1600000US7210334,"Caguas zona urbana, Puerto Rico",36911,1998,36911,(X),32415,1947,87.8,3.0,...,2021,4336,1279,50.3,12.5,4616,1278,(X),(X),NaN
643,1600000US7214290,"Carolina zona urbana, Puerto Rico",72023,2021,72023,(X),60265,2552,83.7,2.4,...,2021,5819,1431,40.9,8.5,4192,1382,(X),(X),NaN
644,1600000US7232522,"Guaynabo zona urbana, Puerto Rico",33545,1246,33545,(X),29229,1640,87.1,3.9,...,2021,2670,989,38.1,11.8,2132,686,(X),(X),NaN
645,1600000US7263820,"Ponce zona urbana, Puerto Rico",56582,1459,56582,(X),45731,1852,80.8,2.2,...,2021,4419,1101,45.5,9.5,6404,790,(X),(X),NaN
646,1600000US7276770,"San Juan zona urbana, Puerto Rico",187754,2747,187754,(X),151134,3523,80.5,1.4,...,2021,24418,2452,45.3,3.6,19470,3032,(X),(X),NaN

In [ ]:

    temp=pd.read_csv(filename, low_memory=False)
    acled_merge=pd.concat([acled_merge, temp])
    print('For csv file',i , 'there are', len(temp['country'].unique()), 'unique countries')
    unique_countries.append(len(temp['country'].unique()))

# To-do
- Matplotlib
- Pivot table. (general intro and recap and how pivot table is often the intermediary to plots)
- Histogram.		Using 2022 data
                    DP04_0017E Year housing built 2020 or later
                    DP04_0018E 2010 to 2019
                    DP04_0019E 2000 to 2009
                    DP04_0020E 1990 to 1999
                    DP04_0021E 1980 to 1989
                    DP04_0022E 1970 to 1979
                    DP04_0023E 1960 to 1969
                    DP04_0024E 1950 to 1959
                    DP04_0025E 1940 to 1949
                    DP04_0026E 1939 or earlier 
- Scatterplots.     DP04_0001E	Estimate!!HOUSING OCCUPANCY!!Total housing units
- Time series.
                    DP04_0045E	Estimate!!HOUSING TENURE!!Occupied housing units
                    DP04_0046E	Estimate!!HOUSING TENURE!!Occupied housing units!!Owner-occupied
                    DP04_0047E	Estimate!!HOUSING TENURE!!Occupied housing units!!Renter-occupied
- Multiple groups.
                    state
                    DP04_0002E	Estimate!!HOUSING OCCUPANCY!!Total housing units!!Occupied housing units
- More than two variables. 	Column Name	Label
                    DP04_0002E	Estimate!!HOUSING OCCUPANCY!!Total housing units!!Occupied housing units
                    DP04_0003E	Estimate!!HOUSING OCCUPANCY!!Total housing units!!Vacant housing units

- Want to use ACS housing data for place (dp04), track things over time. will put variables of interest in parentheses above.
-missing 2020...